version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Natcha
      MYSQL_USER: root
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes:
  mysql_data:
